# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from backlog_client.models.get_watching200_response_issue import GetWatching200ResponseIssue
from typing import Optional, Set
from typing_extensions import Self

class GetWatching200Response(BaseModel):
    """
    GetWatching200Response
    """ # noqa: E501
    id: Optional[StrictInt] = None
    already_read: Optional[StrictBool] = Field(default=None, alias="alreadyRead")
    note: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    issue: Optional[GetWatching200ResponseIssue] = None
    last_content_updated: Optional[datetime] = Field(default=None, alias="lastContentUpdated")
    created: Optional[datetime] = None
    updated: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "alreadyRead", "note", "type", "issue", "lastContentUpdated", "created", "updated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetWatching200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of issue
        if self.issue:
            _dict['issue'] = self.issue.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetWatching200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "alreadyRead": obj.get("alreadyRead"),
            "note": obj.get("note"),
            "type": obj.get("type"),
            "issue": GetWatching200ResponseIssue.from_dict(obj["issue"]) if obj.get("issue") is not None else None,
            "lastContentUpdated": obj.get("lastContentUpdated"),
            "created": obj.get("created"),
            "updated": obj.get("updated")
        })
        return _obj


