# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from backlog_client.models.get_user_activities200_response_inner_content_changes_inner import GetUserActivities200ResponseInnerContentChangesInner
from backlog_client.models.get_user_activities200_response_inner_content_comment import GetUserActivities200ResponseInnerContentComment
from typing import Optional, Set
from typing_extensions import Self

class GetUserActivities200ResponseInnerContent(BaseModel):
    """
    GetUserActivities200ResponseInnerContent
    """ # noqa: E501
    id: Optional[StrictInt] = None
    key_id: Optional[StrictInt] = None
    summary: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    comment: Optional[GetUserActivities200ResponseInnerContentComment] = None
    changes: Optional[List[GetUserActivities200ResponseInnerContentChangesInner]] = None
    __properties: ClassVar[List[str]] = ["id", "key_id", "summary", "description", "comment", "changes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUserActivities200ResponseInnerContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of comment
        if self.comment:
            _dict['comment'] = self.comment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in changes (list)
        _items = []
        if self.changes:
            for _item_changes in self.changes:
                if _item_changes:
                    _items.append(_item_changes.to_dict())
            _dict['changes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUserActivities200ResponseInnerContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "key_id": obj.get("key_id"),
            "summary": obj.get("summary"),
            "description": obj.get("description"),
            "comment": GetUserActivities200ResponseInnerContentComment.from_dict(obj["comment"]) if obj.get("comment") is not None else None,
            "changes": [GetUserActivities200ResponseInnerContentChangesInner.from_dict(_item) for _item in obj["changes"]] if obj.get("changes") is not None else None
        })
        return _obj


