# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from backlog_client.models.get_issue_comment_notifications200_response_inner_user import GetIssueCommentNotifications200ResponseInnerUser
from backlog_client.models.get_pull_request_comments200_response_inner_change_log_inner import GetPullRequestComments200ResponseInnerChangeLogInner
from typing import Optional, Set
from typing_extensions import Self

class GetPullRequestComments200ResponseInner(BaseModel):
    """
    GetPullRequestComments200ResponseInner
    """ # noqa: E501
    id: Optional[StrictInt] = None
    content: Optional[StrictStr] = None
    change_log: Optional[List[GetPullRequestComments200ResponseInnerChangeLogInner]] = Field(default=None, alias="changeLog")
    created_user: Optional[GetIssueCommentNotifications200ResponseInnerUser] = Field(default=None, alias="createdUser")
    created: Optional[datetime] = None
    updated: Optional[datetime] = None
    stars: Optional[List[Dict[str, Any]]] = None
    notifications: Optional[List[Dict[str, Any]]] = None
    __properties: ClassVar[List[str]] = ["id", "content", "changeLog", "createdUser", "created", "updated", "stars", "notifications"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetPullRequestComments200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in change_log (list)
        _items = []
        if self.change_log:
            for _item_change_log in self.change_log:
                if _item_change_log:
                    _items.append(_item_change_log.to_dict())
            _dict['changeLog'] = _items
        # override the default output from pydantic by calling `to_dict()` of created_user
        if self.created_user:
            _dict['createdUser'] = self.created_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetPullRequestComments200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "content": obj.get("content"),
            "changeLog": [GetPullRequestComments200ResponseInnerChangeLogInner.from_dict(_item) for _item in obj["changeLog"]] if obj.get("changeLog") is not None else None,
            "createdUser": GetIssueCommentNotifications200ResponseInnerUser.from_dict(obj["createdUser"]) if obj.get("createdUser") is not None else None,
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "stars": obj.get("stars"),
            "notifications": obj.get("notifications")
        })
        return _obj


