# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from backlog_client.models.delete_pull_request_attachment200_response import DeletePullRequestAttachment200Response
from backlog_client.models.get_issue200_response_priority import GetIssue200ResponsePriority
from backlog_client.models.update_wiki200_response_shared_files_inner import UpdateWiki200ResponseSharedFilesInner
from backlog_client.models.user import User
from typing import Optional, Set
from typing_extensions import Self

class UpdateWiki200Response(BaseModel):
    """
    UpdateWiki200Response
    """ # noqa: E501
    id: Optional[StrictInt] = None
    project_id: Optional[StrictInt] = Field(default=None, alias="projectId")
    name: Optional[StrictStr] = None
    content: Optional[StrictStr] = None
    tags: Optional[List[GetIssue200ResponsePriority]] = None
    attachments: Optional[List[DeletePullRequestAttachment200Response]] = None
    shared_files: Optional[List[UpdateWiki200ResponseSharedFilesInner]] = Field(default=None, alias="sharedFiles")
    stars: Optional[List[Dict[str, Any]]] = None
    created_user: Optional[User] = Field(default=None, alias="createdUser")
    created: Optional[datetime] = None
    updated_user: Optional[User] = Field(default=None, alias="updatedUser")
    updated: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "projectId", "name", "content", "tags", "attachments", "sharedFiles", "stars", "createdUser", "created", "updatedUser", "updated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateWiki200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shared_files (list)
        _items = []
        if self.shared_files:
            for _item_shared_files in self.shared_files:
                if _item_shared_files:
                    _items.append(_item_shared_files.to_dict())
            _dict['sharedFiles'] = _items
        # override the default output from pydantic by calling `to_dict()` of created_user
        if self.created_user:
            _dict['createdUser'] = self.created_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_user
        if self.updated_user:
            _dict['updatedUser'] = self.updated_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateWiki200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "projectId": obj.get("projectId"),
            "name": obj.get("name"),
            "content": obj.get("content"),
            "tags": [GetIssue200ResponsePriority.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "attachments": [DeletePullRequestAttachment200Response.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "sharedFiles": [UpdateWiki200ResponseSharedFilesInner.from_dict(_item) for _item in obj["sharedFiles"]] if obj.get("sharedFiles") is not None else None,
            "stars": obj.get("stars"),
            "createdUser": User.from_dict(obj["createdUser"]) if obj.get("createdUser") is not None else None,
            "created": obj.get("created"),
            "updatedUser": User.from_dict(obj["updatedUser"]) if obj.get("updatedUser") is not None else None,
            "updated": obj.get("updated")
        })
        return _obj


