# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_recently_viewed_issues200_response_issue_milestone_inner import GetRecentlyViewedIssues200ResponseIssueMilestoneInner

class TestGetRecentlyViewedIssues200ResponseIssueMilestoneInner(unittest.TestCase):
    """GetRecentlyViewedIssues200ResponseIssueMilestoneInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecentlyViewedIssues200ResponseIssueMilestoneInner:
        """Test GetRecentlyViewedIssues200ResponseIssueMilestoneInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecentlyViewedIssues200ResponseIssueMilestoneInner`
        """
        model = GetRecentlyViewedIssues200ResponseIssueMilestoneInner()
        if include_optional:
            return GetRecentlyViewedIssues200ResponseIssueMilestoneInner(
                id = 56,
                project_id = 56,
                name = '',
                description = '',
                start_date = '',
                release_due_date = '',
                archived = True
            )
        else:
            return GetRecentlyViewedIssues200ResponseIssueMilestoneInner(
        )
        """

    def testGetRecentlyViewedIssues200ResponseIssueMilestoneInner(self):
        """Test GetRecentlyViewedIssues200ResponseIssueMilestoneInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
