# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issues200_response_inner_milestone_inner import GetIssues200ResponseInnerMilestoneInner

class TestGetIssues200ResponseInnerMilestoneInner(unittest.TestCase):
    """GetIssues200ResponseInnerMilestoneInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssues200ResponseInnerMilestoneInner:
        """Test GetIssues200ResponseInnerMilestoneInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssues200ResponseInnerMilestoneInner`
        """
        model = GetIssues200ResponseInnerMilestoneInner()
        if include_optional:
            return GetIssues200ResponseInnerMilestoneInner(
                id = 56,
                project_id = 56,
                name = '',
                description = '',
                start_date = '',
                release_due_date = '',
                archived = True,
                display_order = 56
            )
        else:
            return GetIssues200ResponseInnerMilestoneInner(
        )
        """

    def testGetIssues200ResponseInnerMilestoneInner(self):
        """Test GetIssues200ResponseInnerMilestoneInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
