# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_project_disk_usage200_response import GetProjectDiskUsage200Response

class TestGetProjectDiskUsage200Response(unittest.TestCase):
    """GetProjectDiskUsage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectDiskUsage200Response:
        """Test GetProjectDiskUsage200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProjectDiskUsage200Response`
        """
        model = GetProjectDiskUsage200Response()
        if include_optional:
            return GetProjectDiskUsage200Response(
                project_id = 56,
                issue = 56,
                wiki = 56,
                file = 56,
                subversion = 56,
                git = 56,
                git_lfs = 56
            )
        else:
            return GetProjectDiskUsage200Response(
        )
        """

    def testGetProjectDiskUsage200Response(self):
        """Test GetProjectDiskUsage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
