# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_pull_request200_response_issue import GetPullRequest200ResponseIssue

class TestGetPullRequest200ResponseIssue(unittest.TestCase):
    """GetPullRequest200ResponseIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPullRequest200ResponseIssue:
        """Test GetPullRequest200ResponseIssue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPullRequest200ResponseIssue`
        """
        model = GetPullRequest200ResponseIssue()
        if include_optional:
            return GetPullRequest200ResponseIssue(
                id = 56,
                project_id = 56,
                issue_key = '',
                key_id = 56,
                summary = '',
                description = ''
            )
        else:
            return GetPullRequest200ResponseIssue(
        )
        """

    def testGetPullRequest200ResponseIssue(self):
        """Test GetPullRequest200ResponseIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
