# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_notifications200_response_inner_issue import GetNotifications200ResponseInnerIssue

class TestGetNotifications200ResponseInnerIssue(unittest.TestCase):
    """GetNotifications200ResponseInnerIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNotifications200ResponseInnerIssue:
        """Test GetNotifications200ResponseInnerIssue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNotifications200ResponseInnerIssue`
        """
        model = GetNotifications200ResponseInnerIssue()
        if include_optional:
            return GetNotifications200ResponseInnerIssue(
                id = 56,
                project_id = 56,
                issue_key = '',
                key_id = 56,
                summary = '',
                description = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                estimated_hours = 1.337,
                actual_hours = 1.337,
                parent_issue_id = 56,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetNotifications200ResponseInnerIssue(
        )
        """

    def testGetNotifications200ResponseInnerIssue(self):
        """Test GetNotifications200ResponseInnerIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
