# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issues200_response_inner_issue_type import GetIssues200ResponseInnerIssueType

class TestGetIssues200ResponseInnerIssueType(unittest.TestCase):
    """GetIssues200ResponseInnerIssueType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssues200ResponseInnerIssueType:
        """Test GetIssues200ResponseInnerIssueType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssues200ResponseInnerIssueType`
        """
        model = GetIssues200ResponseInnerIssueType()
        if include_optional:
            return GetIssues200ResponseInnerIssueType(
                id = 56,
                project_id = 56,
                name = '',
                color = '',
                display_order = 56
            )
        else:
            return GetIssues200ResponseInnerIssueType(
        )
        """

    def testGetIssues200ResponseInnerIssueType(self):
        """Test GetIssues200ResponseInnerIssueType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
