# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.create_issue201_response_assignee import CreateIssue201ResponseAssignee

class TestCreateIssue201ResponseAssignee(unittest.TestCase):
    """CreateIssue201ResponseAssignee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIssue201ResponseAssignee:
        """Test CreateIssue201ResponseAssignee
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIssue201ResponseAssignee`
        """
        model = CreateIssue201ResponseAssignee()
        if include_optional:
            return CreateIssue201ResponseAssignee(
                id = 56,
                user_id = '',
                name = '',
                role_type = 56
            )
        else:
            return CreateIssue201ResponseAssignee(
        )
        """

    def testCreateIssue201ResponseAssignee(self):
        """Test CreateIssue201ResponseAssignee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
