# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_recently_viewed_issues200_response_issue_stars_inner import GetRecentlyViewedIssues200ResponseIssueStarsInner

class TestGetRecentlyViewedIssues200ResponseIssueStarsInner(unittest.TestCase):
    """GetRecentlyViewedIssues200ResponseIssueStarsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecentlyViewedIssues200ResponseIssueStarsInner:
        """Test GetRecentlyViewedIssues200ResponseIssueStarsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecentlyViewedIssues200ResponseIssueStarsInner`
        """
        model = GetRecentlyViewedIssues200ResponseIssueStarsInner()
        if include_optional:
            return GetRecentlyViewedIssues200ResponseIssueStarsInner(
                id = 56,
                comment = '',
                url = '',
                title = '',
                presenter = backlog_client.models.get_issue_comment_notifications_200_response_inner_user.getIssueCommentNotifications_200_response_inner_user(
                    id = 56, 
                    user_id = '', 
                    name = '', 
                    role_type = 56, 
                    lang = '', 
                    nulab_account = backlog_client.models.get_issue_comment_notifications_200_response_inner_user_nulab_account.getIssueCommentNotifications_200_response_inner_user_nulabAccount(
                        nulab_id = '', 
                        name = '', 
                        unique_id = '', ), 
                    mail_address = '', 
                    last_login_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetRecentlyViewedIssues200ResponseIssueStarsInner(
        )
        """

    def testGetRecentlyViewedIssues200ResponseIssueStarsInner(self):
        """Test GetRecentlyViewedIssues200ResponseIssueStarsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
