# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_user_activities200_response_inner_content_comment import GetUserActivities200ResponseInnerContentComment

class TestGetUserActivities200ResponseInnerContentComment(unittest.TestCase):
    """GetUserActivities200ResponseInnerContentComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserActivities200ResponseInnerContentComment:
        """Test GetUserActivities200ResponseInnerContentComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserActivities200ResponseInnerContentComment`
        """
        model = GetUserActivities200ResponseInnerContentComment()
        if include_optional:
            return GetUserActivities200ResponseInnerContentComment(
                id = 56,
                content = ''
            )
        else:
            return GetUserActivities200ResponseInnerContentComment(
        )
        """

    def testGetUserActivities200ResponseInnerContentComment(self):
        """Test GetUserActivities200ResponseInnerContentComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
