# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_activity200_response import GetActivity200Response

class TestGetActivity200Response(unittest.TestCase):
    """GetActivity200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetActivity200Response:
        """Test GetActivity200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetActivity200Response`
        """
        model = GetActivity200Response()
        if include_optional:
            return GetActivity200Response(
                id = 56,
                project = backlog_client.models.get_user_activities_200_response_inner_project.getUserActivities_200_response_inner_project(
                    id = 56, 
                    project_key = '', 
                    name = '', 
                    chart_enabled = True, 
                    use_resolved_for_chart = True, 
                    subtasking_enabled = True, 
                    project_leader_can_edit_project_leader = True, 
                    use_wiki = True, 
                    use_file_sharing = True, 
                    use_wiki_tree_view = True, 
                    use_original_image_size_at_wiki = True, 
                    text_formatting_rule = '', 
                    archived = True, 
                    display_order = 56, 
                    use_dev_attributes = True, ),
                type = 56,
                content = backlog_client.models.get_user_activities_200_response_inner_content.getUserActivities_200_response_inner_content(
                    id = 56, 
                    key_id = 56, 
                    summary = '', 
                    description = '', 
                    comment = backlog_client.models.get_user_activities_200_response_inner_content_comment.getUserActivities_200_response_inner_content_comment(
                        id = 56, 
                        content = '', ), 
                    changes = [
                        backlog_client.models.get_user_activities_200_response_inner_content_changes_inner.getUserActivities_200_response_inner_content_changes_inner(
                            field = '', 
                            new_value = '', 
                            old_value = '', 
                            type = '', )
                        ], ),
                notifications = [
                    backlog_client.models.get_activity_200_response_notifications_inner.getActivity_200_response_notifications_inner(
                        id = 56, 
                        already_read = True, 
                        reason = 56, 
                        user = backlog_client.models.get_groups_200_response_inner_created_user.getGroups_200_response_inner_createdUser(
                            id = 56, 
                            user_id = '', 
                            name = '', 
                            role_type = 56, 
                            lang = '', 
                            nulab_account = backlog_client.models.get_groups_200_response_inner_members_inner_nulab_account.getGroups_200_response_inner_members_inner_nulabAccount(
                                nulab_id = '', 
                                name = '', 
                                unique_id = '', ), 
                            mail_address = '', 
                            last_login_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ],
                created_user = backlog_client.models.get_groups_200_response_inner_created_user.getGroups_200_response_inner_createdUser(
                    id = 56, 
                    user_id = '', 
                    name = '', 
                    role_type = 56, 
                    lang = '', 
                    nulab_account = backlog_client.models.get_groups_200_response_inner_members_inner_nulab_account.getGroups_200_response_inner_members_inner_nulabAccount(
                        nulab_id = '', 
                        name = '', 
                        unique_id = '', ), 
                    mail_address = '', 
                    last_login_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetActivity200Response(
        )
        """

    def testGetActivity200Response(self):
        """Test GetActivity200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
