# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issue_comment_notifications200_response_inner_user_nulab_account import GetIssueCommentNotifications200ResponseInnerUserNulabAccount

class TestGetIssueCommentNotifications200ResponseInnerUserNulabAccount(unittest.TestCase):
    """GetIssueCommentNotifications200ResponseInnerUserNulabAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssueCommentNotifications200ResponseInnerUserNulabAccount:
        """Test GetIssueCommentNotifications200ResponseInnerUserNulabAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssueCommentNotifications200ResponseInnerUserNulabAccount`
        """
        model = GetIssueCommentNotifications200ResponseInnerUserNulabAccount()
        if include_optional:
            return GetIssueCommentNotifications200ResponseInnerUserNulabAccount(
                nulab_id = '',
                name = '',
                unique_id = ''
            )
        else:
            return GetIssueCommentNotifications200ResponseInnerUserNulabAccount(
        )
        """

    def testGetIssueCommentNotifications200ResponseInnerUserNulabAccount(self):
        """Test GetIssueCommentNotifications200ResponseInnerUserNulabAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
