# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_space_disk_usage200_response_details_inner import GetSpaceDiskUsage200ResponseDetailsInner

class TestGetSpaceDiskUsage200ResponseDetailsInner(unittest.TestCase):
    """GetSpaceDiskUsage200ResponseDetailsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSpaceDiskUsage200ResponseDetailsInner:
        """Test GetSpaceDiskUsage200ResponseDetailsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSpaceDiskUsage200ResponseDetailsInner`
        """
        model = GetSpaceDiskUsage200ResponseDetailsInner()
        if include_optional:
            return GetSpaceDiskUsage200ResponseDetailsInner(
                project_id = 56,
                issue = 56,
                wiki = 56,
                file = 56,
                subversion = 56,
                git = 56,
                git_lfs = 56
            )
        else:
            return GetSpaceDiskUsage200ResponseDetailsInner(
        )
        """

    def testGetSpaceDiskUsage200ResponseDetailsInner(self):
        """Test GetSpaceDiskUsage200ResponseDetailsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
