# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_space200_response import GetSpace200Response

class TestGetSpace200Response(unittest.TestCase):
    """GetSpace200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSpace200Response:
        """Test GetSpace200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSpace200Response`
        """
        model = GetSpace200Response()
        if include_optional:
            return GetSpace200Response(
                space_key = 'nulab',
                name = 'Nulab Inc.',
                owner_id = 1,
                lang = 'ja',
                timezone = 'Asia/Tokyo',
                report_send_time = '08:00:00',
                text_formatting_rule = 'markdown',
                created = '2008-07-06T15:00Z',
                updated = '2013-06-18T07:55:37Z'
            )
        else:
            return GetSpace200Response(
        )
        """

    def testGetSpace200Response(self):
        """Test GetSpace200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
