# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issues200_response_inner_shared_files_inner import GetIssues200ResponseInnerSharedFilesInner

class TestGetIssues200ResponseInnerSharedFilesInner(unittest.TestCase):
    """GetIssues200ResponseInnerSharedFilesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssues200ResponseInnerSharedFilesInner:
        """Test GetIssues200ResponseInnerSharedFilesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssues200ResponseInnerSharedFilesInner`
        """
        model = GetIssues200ResponseInnerSharedFilesInner()
        if include_optional:
            return GetIssues200ResponseInnerSharedFilesInner(
                id = 56,
                project_id = 56,
                type = '',
                dir = '',
                name = '',
                size = 56,
                created_user = None,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_user = None,
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetIssues200ResponseInnerSharedFilesInner(
        )
        """

    def testGetIssues200ResponseInnerSharedFilesInner(self):
        """Test GetIssues200ResponseInnerSharedFilesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
