# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_activity200_response_content_changes_inner import GetActivity200ResponseContentChangesInner

class TestGetActivity200ResponseContentChangesInner(unittest.TestCase):
    """GetActivity200ResponseContentChangesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetActivity200ResponseContentChangesInner:
        """Test GetActivity200ResponseContentChangesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetActivity200ResponseContentChangesInner`
        """
        model = GetActivity200ResponseContentChangesInner()
        if include_optional:
            return GetActivity200ResponseContentChangesInner(
                var_field = '',
                new_value = '',
                old_value = '',
                type = ''
            )
        else:
            return GetActivity200ResponseContentChangesInner(
        )
        """

    def testGetActivity200ResponseContentChangesInner(self):
        """Test GetActivity200ResponseContentChangesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
