# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_pull_requests200_response_inner_issue import GetPullRequests200ResponseInnerIssue

class TestGetPullRequests200ResponseInnerIssue(unittest.TestCase):
    """GetPullRequests200ResponseInnerIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPullRequests200ResponseInnerIssue:
        """Test GetPullRequests200ResponseInnerIssue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPullRequests200ResponseInnerIssue`
        """
        model = GetPullRequests200ResponseInnerIssue()
        if include_optional:
            return GetPullRequests200ResponseInnerIssue(
                id = 56
            )
        else:
            return GetPullRequests200ResponseInnerIssue(
        )
        """

    def testGetPullRequests200ResponseInnerIssue(self):
        """Test GetPullRequests200ResponseInnerIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
