# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_pull_request_comments200_response_inner_change_log_inner import GetPullRequestComments200ResponseInnerChangeLogInner

class TestGetPullRequestComments200ResponseInnerChangeLogInner(unittest.TestCase):
    """GetPullRequestComments200ResponseInnerChangeLogInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPullRequestComments200ResponseInnerChangeLogInner:
        """Test GetPullRequestComments200ResponseInnerChangeLogInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPullRequestComments200ResponseInnerChangeLogInner`
        """
        model = GetPullRequestComments200ResponseInnerChangeLogInner()
        if include_optional:
            return GetPullRequestComments200ResponseInnerChangeLogInner(
                var_field = '',
                new_value = '',
                original_value = ''
            )
        else:
            return GetPullRequestComments200ResponseInnerChangeLogInner(
        )
        """

    def testGetPullRequestComments200ResponseInnerChangeLogInner(self):
        """Test GetPullRequestComments200ResponseInnerChangeLogInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
