# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_user_activities200_response_inner_content import GetUserActivities200ResponseInnerContent

class TestGetUserActivities200ResponseInnerContent(unittest.TestCase):
    """GetUserActivities200ResponseInnerContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserActivities200ResponseInnerContent:
        """Test GetUserActivities200ResponseInnerContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserActivities200ResponseInnerContent`
        """
        model = GetUserActivities200ResponseInnerContent()
        if include_optional:
            return GetUserActivities200ResponseInnerContent(
                id = 56,
                key_id = 56,
                summary = '',
                description = '',
                comment = backlog_client.models.get_user_activities_200_response_inner_content_comment.getUserActivities_200_response_inner_content_comment(
                    id = 56, 
                    content = '', ),
                changes = [
                    backlog_client.models.get_user_activities_200_response_inner_content_changes_inner.getUserActivities_200_response_inner_content_changes_inner(
                        field = '', 
                        new_value = '', 
                        old_value = '', 
                        type = '', )
                    ]
            )
        else:
            return GetUserActivities200ResponseInnerContent(
        )
        """

    def testGetUserActivities200ResponseInnerContent(self):
        """Test GetUserActivities200ResponseInnerContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
