# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_wiki_attachments200_response_inner import GetWikiAttachments200ResponseInner

class TestGetWikiAttachments200ResponseInner(unittest.TestCase):
    """GetWikiAttachments200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWikiAttachments200ResponseInner:
        """Test GetWikiAttachments200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWikiAttachments200ResponseInner`
        """
        model = GetWikiAttachments200ResponseInner()
        if include_optional:
            return GetWikiAttachments200ResponseInner(
                id = 56,
                name = '',
                size = 56
            )
        else:
            return GetWikiAttachments200ResponseInner(
                id = 56,
                name = '',
                size = 56,
        )
        """

    def testGetWikiAttachments200ResponseInner(self):
        """Test GetWikiAttachments200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
