# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.add_custom_field_request_min import AddCustomFieldRequestMin

class TestAddCustomFieldRequestMin(unittest.TestCase):
    """AddCustomFieldRequestMin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddCustomFieldRequestMin:
        """Test AddCustomFieldRequestMin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddCustomFieldRequestMin`
        """
        model = AddCustomFieldRequestMin()
        if include_optional:
            return AddCustomFieldRequestMin(
            )
        else:
            return AddCustomFieldRequestMin(
        )
        """

    def testAddCustomFieldRequestMin(self):
        """Test AddCustomFieldRequestMin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
