# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.add_custom_field200_response import AddCustomField200Response

class TestAddCustomField200Response(unittest.TestCase):
    """AddCustomField200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddCustomField200Response:
        """Test AddCustomField200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddCustomField200Response`
        """
        model = AddCustomField200Response()
        if include_optional:
            return AddCustomField200Response(
                id = 56,
                project_id = 56,
                type_id = 56,
                name = '',
                description = '',
                required = True,
                applicable_issue_types = [
                    56
                    ]
            )
        else:
            return AddCustomField200Response(
        )
        """

    def testAddCustomField200Response(self):
        """Test AddCustomField200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
