# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_activity200_response_content import GetActivity200ResponseContent

class TestGetActivity200ResponseContent(unittest.TestCase):
    """GetActivity200ResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetActivity200ResponseContent:
        """Test GetActivity200ResponseContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetActivity200ResponseContent`
        """
        model = GetActivity200ResponseContent()
        if include_optional:
            return GetActivity200ResponseContent(
                id = 56,
                key_id = 56,
                summary = '',
                description = '',
                comment = backlog_client.models.get_activity_200_response_content_comment.getActivity_200_response_content_comment(
                    id = 56, 
                    content = '', ),
                changes = [
                    backlog_client.models.get_activity_200_response_content_changes_inner.getActivity_200_response_content_changes_inner(
                        field = '', 
                        new_value = '', 
                        old_value = '', 
                        type = '', )
                    ]
            )
        else:
            return GetActivity200ResponseContent(
        )
        """

    def testGetActivity200ResponseContent(self):
        """Test GetActivity200ResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
