# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_statuses200_response_inner import GetStatuses200ResponseInner

class TestGetStatuses200ResponseInner(unittest.TestCase):
    """GetStatuses200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatuses200ResponseInner:
        """Test GetStatuses200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatuses200ResponseInner`
        """
        model = GetStatuses200ResponseInner()
        if include_optional:
            return GetStatuses200ResponseInner(
                id = 1,
                name = '未対応'
            )
        else:
            return GetStatuses200ResponseInner(
        )
        """

    def testGetStatuses200ResponseInner(self):
        """Test GetStatuses200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
