# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_notifications200_response_inner_comment import GetNotifications200ResponseInnerComment

class TestGetNotifications200ResponseInnerComment(unittest.TestCase):
    """GetNotifications200ResponseInnerComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNotifications200ResponseInnerComment:
        """Test GetNotifications200ResponseInnerComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNotifications200ResponseInnerComment`
        """
        model = GetNotifications200ResponseInnerComment()
        if include_optional:
            return GetNotifications200ResponseInnerComment(
                id = 56,
                project_id = 56,
                issue_id = 56,
                content = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetNotifications200ResponseInnerComment(
        )
        """

    def testGetNotifications200ResponseInnerComment(self):
        """Test GetNotifications200ResponseInnerComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
