# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_custom_fields200_response_inner import GetCustomFields200ResponseInner

class TestGetCustomFields200ResponseInner(unittest.TestCase):
    """GetCustomFields200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCustomFields200ResponseInner:
        """Test GetCustomFields200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCustomFields200ResponseInner`
        """
        model = GetCustomFields200ResponseInner()
        if include_optional:
            return GetCustomFields200ResponseInner(
                id = 56,
                project_id = 56,
                type_id = 56,
                name = '',
                description = '',
                required = True,
                applicable_issue_types = [
                    56
                    ],
                allow_add_item = True,
                items = [
                    backlog_client.models.get_custom_fields_200_response_inner_items_inner.getCustomFields_200_response_inner_items_inner(
                        id = 56, 
                        name = '', 
                        display_order = 56, )
                    ]
            )
        else:
            return GetCustomFields200ResponseInner(
        )
        """

    def testGetCustomFields200ResponseInner(self):
        """Test GetCustomFields200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
