# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.post_attachment200_response import PostAttachment200Response

class TestPostAttachment200Response(unittest.TestCase):
    """PostAttachment200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAttachment200Response:
        """Test PostAttachment200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAttachment200Response`
        """
        model = PostAttachment200Response()
        if include_optional:
            return PostAttachment200Response(
                id = 1,
                name = 'test.txt',
                size = 8857
            )
        else:
            return PostAttachment200Response(
        )
        """

    def testPostAttachment200Response(self):
        """Test PostAttachment200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
