# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_licence_info200_response import GetLicenceInfo200Response

class TestGetLicenceInfo200Response(unittest.TestCase):
    """GetLicenceInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLicenceInfo200Response:
        """Test GetLicenceInfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLicenceInfo200Response`
        """
        model = GetLicenceInfo200Response()
        if include_optional:
            return GetLicenceInfo200Response(
                active = True,
                attachment_limit = 56,
                attachment_limit_per_file = 56,
                attachment_num_limit = 56,
                attribute = True,
                attribute_limit = 56,
                burndown = True,
                comment_limit = 56,
                component_limit = 56,
                file_sharing = True,
                gantt = True,
                git = True,
                issue_limit = 56,
                licence_type_id = 56,
                limit_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                nulab_account = True,
                parent_child_issue = True,
                post_issue_by_mail = True,
                project_limit = 56,
                pull_request_attachment_limit_per_file = 56,
                pull_request_attachment_num_limit = 56,
                remote_address = True,
                remote_address_limit = 56,
                started_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                storage_limit = 56,
                subversion = True,
                subversion_external = True,
                user_limit = 56,
                version_limit = 56,
                wiki_attachment = True,
                wiki_attachment_limit_per_file = 56,
                wiki_attachment_num_limit = 56
            )
        else:
            return GetLicenceInfo200Response(
        )
        """

    def testGetLicenceInfo200Response(self):
        """Test GetLicenceInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
