# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_groups200_response_inner_members_inner_nulab_account import GetGroups200ResponseInnerMembersInnerNulabAccount

class TestGetGroups200ResponseInnerMembersInnerNulabAccount(unittest.TestCase):
    """GetGroups200ResponseInnerMembersInnerNulabAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGroups200ResponseInnerMembersInnerNulabAccount:
        """Test GetGroups200ResponseInnerMembersInnerNulabAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGroups200ResponseInnerMembersInnerNulabAccount`
        """
        model = GetGroups200ResponseInnerMembersInnerNulabAccount()
        if include_optional:
            return GetGroups200ResponseInnerMembersInnerNulabAccount(
                nulab_id = '',
                name = '',
                unique_id = ''
            )
        else:
            return GetGroups200ResponseInnerMembersInnerNulabAccount(
        )
        """

    def testGetGroups200ResponseInnerMembersInnerNulabAccount(self):
        """Test GetGroups200ResponseInnerMembersInnerNulabAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
