# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.delete_project_status200_response import DeleteProjectStatus200Response

class TestDeleteProjectStatus200Response(unittest.TestCase):
    """DeleteProjectStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteProjectStatus200Response:
        """Test DeleteProjectStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteProjectStatus200Response`
        """
        model = DeleteProjectStatus200Response()
        if include_optional:
            return DeleteProjectStatus200Response(
                id = 56,
                project_id = 56,
                name = '',
                color = '',
                display_order = 56
            )
        else:
            return DeleteProjectStatus200Response(
        )
        """

    def testDeleteProjectStatus200Response(self):
        """Test DeleteProjectStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
