# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issue_types200_response_inner import GetIssueTypes200ResponseInner

class TestGetIssueTypes200ResponseInner(unittest.TestCase):
    """GetIssueTypes200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssueTypes200ResponseInner:
        """Test GetIssueTypes200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssueTypes200ResponseInner`
        """
        model = GetIssueTypes200ResponseInner()
        if include_optional:
            return GetIssueTypes200ResponseInner(
                id = 56,
                project_id = 56,
                name = '',
                color = '',
                display_order = 56,
                template_summary = '',
                template_description = ''
            )
        else:
            return GetIssueTypes200ResponseInner(
        )
        """

    def testGetIssueTypes200ResponseInner(self):
        """Test GetIssueTypes200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
