# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_rate_limit200_response_rate_limit_read import GetRateLimit200ResponseRateLimitRead

class TestGetRateLimit200ResponseRateLimitRead(unittest.TestCase):
    """GetRateLimit200ResponseRateLimitRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimit200ResponseRateLimitRead:
        """Test GetRateLimit200ResponseRateLimitRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimit200ResponseRateLimitRead`
        """
        model = GetRateLimit200ResponseRateLimitRead()
        if include_optional:
            return GetRateLimit200ResponseRateLimitRead(
                limit = 600,
                remaining = 600,
                reset = 1603881873
            )
        else:
            return GetRateLimit200ResponseRateLimitRead(
        )
        """

    def testGetRateLimit200ResponseRateLimitRead(self):
        """Test GetRateLimit200ResponseRateLimitRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
