# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_notifications200_response_inner import GetNotifications200ResponseInner

class TestGetNotifications200ResponseInner(unittest.TestCase):
    """GetNotifications200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNotifications200ResponseInner:
        """Test GetNotifications200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNotifications200ResponseInner`
        """
        model = GetNotifications200ResponseInner()
        if include_optional:
            return GetNotifications200ResponseInner(
                id = 56,
                already_read = True,
                reason = 56,
                resource_already_read = True,
                project = backlog_client.models.get_user_activities_200_response_inner_project.getUserActivities_200_response_inner_project(
                    id = 56, 
                    project_key = '', 
                    name = '', 
                    chart_enabled = True, 
                    use_resolved_for_chart = True, 
                    subtasking_enabled = True, 
                    project_leader_can_edit_project_leader = True, 
                    use_wiki = True, 
                    use_file_sharing = True, 
                    use_wiki_tree_view = True, 
                    use_original_image_size_at_wiki = True, 
                    text_formatting_rule = '', 
                    archived = True, 
                    display_order = 56, 
                    use_dev_attributes = True, ),
                issue = backlog_client.models.get_pull_request_200_response_issue.getPullRequest_200_response_issue(
                    id = 56, 
                    project_id = 56, 
                    issue_key = '', 
                    key_id = 56, 
                    summary = '', 
                    description = '', ),
                comment = backlog_client.models.get_notifications_200_response_inner_comment.getNotifications_200_response_inner_comment(
                    id = 56, 
                    project_id = 56, 
                    issue_id = 56, 
                    content = '', 
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                pull_request = None,
                pull_request_comment = None,
                sender = backlog_client.models.create_issue_201_response_assignee.createIssue_201_response_assignee(
                    id = 56, 
                    user_id = '', 
                    name = '', 
                    role_type = 56, ),
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetNotifications200ResponseInner(
        )
        """

    def testGetNotifications200ResponseInner(self):
        """Test GetNotifications200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
