# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_pull_request200_response_created_user import GetPullRequest200ResponseCreatedUser

class TestGetPullRequest200ResponseCreatedUser(unittest.TestCase):
    """GetPullRequest200ResponseCreatedUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPullRequest200ResponseCreatedUser:
        """Test GetPullRequest200ResponseCreatedUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPullRequest200ResponseCreatedUser`
        """
        model = GetPullRequest200ResponseCreatedUser()
        if include_optional:
            return GetPullRequest200ResponseCreatedUser(
                id = 56,
                user_id = '',
                name = '',
                role_type = 56,
                lang = ''
            )
        else:
            return GetPullRequest200ResponseCreatedUser(
        )
        """

    def testGetPullRequest200ResponseCreatedUser(self):
        """Test GetPullRequest200ResponseCreatedUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
