# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_user_activities200_response_inner_content_changes_inner import GetUserActivities200ResponseInnerContentChangesInner

class TestGetUserActivities200ResponseInnerContentChangesInner(unittest.TestCase):
    """GetUserActivities200ResponseInnerContentChangesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserActivities200ResponseInnerContentChangesInner:
        """Test GetUserActivities200ResponseInnerContentChangesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserActivities200ResponseInnerContentChangesInner`
        """
        model = GetUserActivities200ResponseInnerContentChangesInner()
        if include_optional:
            return GetUserActivities200ResponseInnerContentChangesInner(
                var_field = '',
                new_value = '',
                old_value = '',
                type = ''
            )
        else:
            return GetUserActivities200ResponseInnerContentChangesInner(
        )
        """

    def testGetUserActivities200ResponseInnerContentChangesInner(self):
        """Test GetUserActivities200ResponseInnerContentChangesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
