# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_git_repository200_response_created_user import GetGitRepository200ResponseCreatedUser

class TestGetGitRepository200ResponseCreatedUser(unittest.TestCase):
    """GetGitRepository200ResponseCreatedUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGitRepository200ResponseCreatedUser:
        """Test GetGitRepository200ResponseCreatedUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGitRepository200ResponseCreatedUser`
        """
        model = GetGitRepository200ResponseCreatedUser()
        if include_optional:
            return GetGitRepository200ResponseCreatedUser(
                id = 56,
                user_id = '',
                name = '',
                role_type = 56,
                lang = '',
                nulab_account = backlog_client.models.get_issue_comment_notifications_200_response_inner_user_nulab_account.getIssueCommentNotifications_200_response_inner_user_nulabAccount(
                    nulab_id = '', 
                    name = '', 
                    unique_id = '', ),
                mail_address = '',
                last_login_time = ''
            )
        else:
            return GetGitRepository200ResponseCreatedUser(
        )
        """

    def testGetGitRepository200ResponseCreatedUser(self):
        """Test GetGitRepository200ResponseCreatedUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
