# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issues200_response_inner_stars_inner import GetIssues200ResponseInnerStarsInner

class TestGetIssues200ResponseInnerStarsInner(unittest.TestCase):
    """GetIssues200ResponseInnerStarsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssues200ResponseInnerStarsInner:
        """Test GetIssues200ResponseInnerStarsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssues200ResponseInnerStarsInner`
        """
        model = GetIssues200ResponseInnerStarsInner()
        if include_optional:
            return GetIssues200ResponseInnerStarsInner(
                id = 56,
                comment = '',
                url = '',
                title = '',
                presenter = None,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetIssues200ResponseInnerStarsInner(
        )
        """

    def testGetIssues200ResponseInnerStarsInner(self):
        """Test GetIssues200ResponseInnerStarsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
