# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_projects200_response_inner import GetProjects200ResponseInner

class TestGetProjects200ResponseInner(unittest.TestCase):
    """GetProjects200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjects200ResponseInner:
        """Test GetProjects200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProjects200ResponseInner`
        """
        model = GetProjects200ResponseInner()
        if include_optional:
            return GetProjects200ResponseInner(
                id = 56,
                project_key = '',
                name = '',
                chart_enabled = True,
                use_resolved_for_chart = True,
                subtasking_enabled = True,
                project_leader_can_edit_project_leader = True,
                use_wiki = True,
                use_file_sharing = True,
                use_wiki_tree_view = True,
                use_subversion = True,
                use_git = True,
                use_original_image_size_at_wiki = True,
                text_formatting_rule = '',
                archived = True,
                display_order = 56,
                use_dev_attributes = True
            )
        else:
            return GetProjects200ResponseInner(
        )
        """

    def testGetProjects200ResponseInner(self):
        """Test GetProjects200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
