# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issue200_response_issue_type import GetIssue200ResponseIssueType

class TestGetIssue200ResponseIssueType(unittest.TestCase):
    """GetIssue200ResponseIssueType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssue200ResponseIssueType:
        """Test GetIssue200ResponseIssueType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssue200ResponseIssueType`
        """
        model = GetIssue200ResponseIssueType()
        if include_optional:
            return GetIssue200ResponseIssueType(
                id = 56,
                project_id = 56,
                name = '',
                color = '',
                display_order = 56
            )
        else:
            return GetIssue200ResponseIssueType(
        )
        """

    def testGetIssue200ResponseIssueType(self):
        """Test GetIssue200ResponseIssueType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
