# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_pull_request_comment_count200_response import GetPullRequestCommentCount200Response

class TestGetPullRequestCommentCount200Response(unittest.TestCase):
    """GetPullRequestCommentCount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPullRequestCommentCount200Response:
        """Test GetPullRequestCommentCount200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPullRequestCommentCount200Response`
        """
        model = GetPullRequestCommentCount200Response()
        if include_optional:
            return GetPullRequestCommentCount200Response(
                count = 10
            )
        else:
            return GetPullRequestCommentCount200Response(
        )
        """

    def testGetPullRequestCommentCount200Response(self):
        """Test GetPullRequestCommentCount200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
