# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_issue200_response_priority import GetIssue200ResponsePriority

class TestGetIssue200ResponsePriority(unittest.TestCase):
    """GetIssue200ResponsePriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssue200ResponsePriority:
        """Test GetIssue200ResponsePriority
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssue200ResponsePriority`
        """
        model = GetIssue200ResponsePriority()
        if include_optional:
            return GetIssue200ResponsePriority(
                id = 56,
                name = ''
            )
        else:
            return GetIssue200ResponsePriority(
        )
        """

    def testGetIssue200ResponsePriority(self):
        """Test GetIssue200ResponsePriority"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
