# coding: utf-8

"""
    Backlog API

    Backlog REST API specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from backlog_client.models.get_project_statuses200_response_inner import GetProjectStatuses200ResponseInner

class TestGetProjectStatuses200ResponseInner(unittest.TestCase):
    """GetProjectStatuses200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectStatuses200ResponseInner:
        """Test GetProjectStatuses200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProjectStatuses200ResponseInner`
        """
        model = GetProjectStatuses200ResponseInner()
        if include_optional:
            return GetProjectStatuses200ResponseInner(
                id = 56,
                project_id = 56,
                name = '',
                color = '',
                display_order = 56
            )
        else:
            return GetProjectStatuses200ResponseInner(
                id = 56,
                project_id = 56,
                name = '',
                color = '',
                display_order = 56,
        )
        """

    def testGetProjectStatuses200ResponseInner(self):
        """Test GetProjectStatuses200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
